"""
Redraw closed-loop: linked tasks, revision tracking, and per-family
authoritative write-back.

Write-back targets
------------------
- **satellite_mv**: update one instance in ``instance_map_uint8.png`` +
  ``instances.json`` via ``authoritative_instance_id``.  Rejected candidates
  (``candidate_source == "pre_merge_rejected"``) cannot be correction targets.
- **satellite_ev**: full rewrite of all annotations for the image.
- **stream_ev**: update only ``type == "streams"`` instances; satellites
  are preserved.

``id_map.json`` is NOT patched or regenerated by correction.
"""
from __future__ import annotations

import hashlib
import json
import uuid
from dataclasses import asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import numpy as np
from PIL import Image

from src.review.schemas import (
    CorrectionLink,
    TaskFamily,
    compute_revision_hash_ev,
    compute_revision_hash_sat_mv,
)


# ---------------------------------------------------------------------------
#  CorrectionLinkMap  (correction_link_map.json)
# ---------------------------------------------------------------------------

class CorrectionLinkMap:
    """Persistent map: original_task_revision_id → CorrectionLink."""

    def __init__(self, links: dict[str, CorrectionLink] | None = None) -> None:
        self._links: dict[str, CorrectionLink] = links or {}

    @classmethod
    def load(cls, path: Path) -> CorrectionLinkMap:
        if not path.exists():
            return cls()
        with open(path) as fh:
            raw = json.load(fh)
        links = {}
        for key, val in raw.items():
            links[key] = CorrectionLink(**val)
        return cls(links)

    def save(self, path: Path) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        out: dict[str, Any] = {}
        for key, cl in self._links.items():
            out[key] = {
                "original_task_revision_id": cl.original_task_revision_id,
                "correction_task_revision_id": cl.correction_task_revision_id,
                "original_revision_hash": cl.original_revision_hash,
                "new_revision_hash": cl.new_revision_hash,
                "status": cl.status,
            }
        with open(path, "w") as fh:
            json.dump(out, fh, indent=2)

    def mark_superseded(
        self,
        original_task_revision_id: str,
        original_revision_hash: str,
        new_task_revision_id: str,
        new_revision_hash: str,
    ) -> CorrectionLink:
        link = CorrectionLink(
            original_task_revision_id=original_task_revision_id,
            correction_task_revision_id=new_task_revision_id,
            original_revision_hash=original_revision_hash,
            new_revision_hash=new_revision_hash,
            status="superseded",
        )
        self._links[original_task_revision_id] = link
        return link

    def is_superseded(self, task_revision_id: str) -> bool:
        link = self._links.get(task_revision_id)
        return link is not None and link.status == "superseded"

    def get(self, task_revision_id: str) -> CorrectionLink | None:
        return self._links.get(task_revision_id)


# ---------------------------------------------------------------------------
#  Revision-hash validation
# ---------------------------------------------------------------------------

def _annotation_state_hash(
    instance_map: np.ndarray, instances: list[dict],
) -> str:
    h = hashlib.sha256()
    h.update(instance_map.tobytes())
    h.update(json.dumps(instances, sort_keys=True).encode())
    return h.hexdigest()


def validate_revision_hash(
    record: dict[str, Any],
    gt_dir: Path,
) -> bool:
    """Re-compute revision hash from current state and compare."""
    from src.review.key_adapter import sample_id_to_base_key
    bk = sample_id_to_base_key(record["sample_id"])
    bk_dir = gt_dir / str(bk)

    family = TaskFamily(record["task_family"])

    if family == TaskFamily.SATELLITE_MV:
        arefs = record["asset_refs"]
        ctx_path = bk_dir.parent.parent / arefs["bare_context_path"]
        if ctx_path.exists():
            ctx_sha1 = hashlib.sha1(ctx_path.read_bytes()).hexdigest()
        else:
            ctx_sha1 = arefs["bare_context_sha1"]

        from src.review.schemas import CropSpec
        expected = compute_revision_hash_sat_mv(
            task_family=family,
            sample_id=record["sample_id"],
            task_revision_id=record["task_revision_id"],
            render_spec_id=record["render_spec_id"],
            fixed_prompt_id=record["fixed_prompt_id"],
            candidate_rle=arefs["candidate_rle"],
            candidate_bbox_xywh=tuple(arefs["candidate_bbox_xywh"]),
            crop_spec=CropSpec(**arefs["crop_spec"]),
            bare_context_sha1=ctx_sha1,
            candidate_source=arefs["candidate_source"],
            authoritative_instance_id=arefs.get("authoritative_instance_id"),
        )
    else:
        imap = np.array(Image.open(bk_dir / "instance_map_uint8.png"))
        with open(bk_dir / "instances.json") as f:
            instances = json.load(f)
        ann_hash = _annotation_state_hash(imap, instances)

        img_sha1 = record["asset_refs"]["review_image_sha1"]
        frag_hash = None
        if record["asset_refs"].get("fragment_hints"):
            frag_hash = hashlib.sha256(
                json.dumps(record["asset_refs"]["fragment_hints"],
                           sort_keys=True).encode()
            ).hexdigest()

        expected = compute_revision_hash_ev(
            task_family=family,
            sample_id=record["sample_id"],
            task_revision_id=record["task_revision_id"],
            render_spec_id=record["render_spec_id"],
            fixed_prompt_id=record["fixed_prompt_id"],
            review_image_sha1=img_sha1,
            annotation_state_hash=ann_hash,
            fragment_hints_hash=frag_hash,
            synthetic_variant_id=record["asset_refs"].get("synthetic_variant_id"),
        )

    return expected == record["revision_hash"]


# ---------------------------------------------------------------------------
#  Per-family write-back
# ---------------------------------------------------------------------------

def _write_back_satellite_mv(
    record: dict[str, Any],
    corrected_mask: np.ndarray,
    gt_dir: Path,
) -> None:
    """Update one satellite instance in the authoritative GT layer."""
    arefs = record["asset_refs"]

    if arefs["candidate_source"] == "pre_merge_rejected":
        raise ValueError(
            "Cannot correct a pre_merge_rejected candidate "
            f"(candidate_id={arefs['candidate_id']}); "
            "authoritative_instance_id is None."
        )

    inst_id = arefs["authoritative_instance_id"]
    if inst_id is None:
        raise ValueError("authoritative_instance_id is None")

    from src.review.key_adapter import sample_id_to_base_key
    bk = sample_id_to_base_key(record["sample_id"])
    bk_dir = gt_dir / str(bk)

    imap = np.array(Image.open(bk_dir / "instance_map_uint8.png"))
    imap[imap == inst_id] = 0
    imap[corrected_mask.astype(bool)] = inst_id

    Image.fromarray(imap.astype(np.uint8)).save(bk_dir / "instance_map_uint8.png")


def _write_back_satellite_ev(
    record: dict[str, Any],
    corrected_map: np.ndarray,
    corrected_instances: list[dict],
    gt_dir: Path,
) -> None:
    """Full rewrite of annotations for the image."""
    from src.review.key_adapter import sample_id_to_base_key
    bk = sample_id_to_base_key(record["sample_id"])
    bk_dir = gt_dir / str(bk)

    Image.fromarray(corrected_map.astype(np.uint8)).save(
        bk_dir / "instance_map_uint8.png"
    )
    with open(bk_dir / "instances.json", "w") as f:
        json.dump(corrected_instances, f, indent=2)


def _write_back_stream_ev(
    record: dict[str, Any],
    corrected_stream_masks: dict[int, np.ndarray],
    gt_dir: Path,
) -> None:
    """Update stream instances only; preserve satellites."""
    from src.review.key_adapter import sample_id_to_base_key
    bk = sample_id_to_base_key(record["sample_id"])
    bk_dir = gt_dir / str(bk)

    imap = np.array(Image.open(bk_dir / "instance_map_uint8.png"))
    with open(bk_dir / "instances.json") as f:
        instances = json.load(f)

    stream_ids = {inst["id"] for inst in instances if inst["type"] == "streams"}

    for sid in stream_ids:
        imap[imap == sid] = 0

    new_instances = [inst for inst in instances if inst["type"] != "streams"]

    for sid, mask in corrected_stream_masks.items():
        if sid not in stream_ids:
            raise ValueError(
                f"Instance {sid} is not a stream instance; "
                "stream_ev corrections may NOT modify satellite instances."
            )
        imap[mask.astype(bool)] = sid
        new_instances.append({"id": sid, "type": "streams"})

    Image.fromarray(imap.astype(np.uint8)).save(bk_dir / "instance_map_uint8.png")
    with open(bk_dir / "instances.json", "w") as f:
        json.dump(new_instances, f, indent=2)


# ---------------------------------------------------------------------------
#  Import correction (orchestrator)
# ---------------------------------------------------------------------------

def import_correction(
    record: dict[str, Any],
    corrected_data: dict[str, Any],
    gt_dir: Path,
    link_map: CorrectionLinkMap,
) -> dict[str, Any]:
    """Import one expert correction and update authoritative state.

    Parameters
    ----------
    record
        The original ``VerifierExample`` record (as dict).
    corrected_data
        Family-specific correction payload:
        - satellite_mv: ``{"corrected_mask": np.ndarray}``
        - satellite_ev: ``{"corrected_map": np.ndarray, "corrected_instances": list}``
        - stream_ev: ``{"corrected_stream_masks": dict[int, np.ndarray]}``
    gt_dir
        Root of the authoritative GT layer.
    link_map
        Mutable CorrectionLinkMap to update.

    Returns
    -------
    dict with ``new_task_revision_id``, ``new_revision_hash``,
    ``re_export_keys`` (list of BaseKey strings).
    """
    if not validate_revision_hash(record, gt_dir):
        raise ValueError(
            "Stale revision hash — authoritative state has changed "
            "since this task was created."
        )

    family = TaskFamily(record["task_family"])

    # Synthetic EV write-back guard: only gt_complete, gt_empty, or legacy
    # (None) variants may update authoritative GT.
    if family in (TaskFamily.SATELLITE_EV, TaskFamily.STREAM_EV):
        syn_id = record["asset_refs"].get("synthetic_variant_id")
        _WRITEBACK_SAFE = {"gt_complete", "gt_empty", None}
        if syn_id not in _WRITEBACK_SAFE:
            raise ValueError(
                f"Synthetic variant {syn_id!r} is not write-back safe; "
                f"allowed: {sorted(str(v) for v in _WRITEBACK_SAFE if v)}"
            )

    if family == TaskFamily.SATELLITE_MV:
        _write_back_satellite_mv(record, corrected_data["corrected_mask"], gt_dir)
    elif family == TaskFamily.SATELLITE_EV:
        _write_back_satellite_ev(
            record,
            corrected_data["corrected_map"],
            corrected_data["corrected_instances"],
            gt_dir,
        )
    elif family == TaskFamily.STREAM_EV:
        _write_back_stream_ev(
            record, corrected_data["corrected_stream_masks"], gt_dir,
        )

    new_rev_id = f"rev_{uuid.uuid4().hex[:8]}"

    from src.review.key_adapter import sample_id_to_base_key
    bk = sample_id_to_base_key(record["sample_id"])
    bk_dir = gt_dir / str(bk)
    new_imap = np.array(Image.open(bk_dir / "instance_map_uint8.png"))
    with open(bk_dir / "instances.json") as f:
        new_instances = json.load(f)
    new_ann_hash = _annotation_state_hash(new_imap, new_instances)

    if family == TaskFamily.SATELLITE_MV:
        arefs = record["asset_refs"]
        from src.review.schemas import CropSpec
        new_rev_hash = compute_revision_hash_sat_mv(
            task_family=family,
            sample_id=record["sample_id"],
            task_revision_id=new_rev_id,
            render_spec_id=record["render_spec_id"],
            fixed_prompt_id=record["fixed_prompt_id"],
            candidate_rle=arefs["candidate_rle"],
            candidate_bbox_xywh=tuple(arefs["candidate_bbox_xywh"]),
            crop_spec=CropSpec(**arefs["crop_spec"]),
            bare_context_sha1=arefs["bare_context_sha1"],
            candidate_source=arefs["candidate_source"],
            authoritative_instance_id=arefs.get("authoritative_instance_id"),
        )
    else:
        img_sha1 = record["asset_refs"]["review_image_sha1"]
        frag_hash = None
        if record["asset_refs"].get("fragment_hints"):
            frag_hash = hashlib.sha256(
                json.dumps(record["asset_refs"]["fragment_hints"],
                           sort_keys=True).encode()
            ).hexdigest()
        new_rev_hash = compute_revision_hash_ev(
            task_family=family,
            sample_id=record["sample_id"],
            task_revision_id=new_rev_id,
            render_spec_id=record["render_spec_id"],
            fixed_prompt_id=record["fixed_prompt_id"],
            review_image_sha1=img_sha1,
            annotation_state_hash=new_ann_hash,
            fragment_hints_hash=frag_hash,
            synthetic_variant_id=record["asset_refs"].get("synthetic_variant_id"),
        )

    link_map.mark_superseded(
        original_task_revision_id=record["task_revision_id"],
        original_revision_hash=record["revision_hash"],
        new_task_revision_id=new_rev_id,
        new_revision_hash=new_rev_hash,
    )

    return {
        "new_task_revision_id": new_rev_id,
        "new_revision_hash": new_rev_hash,
        "re_export_keys": [str(bk)],
    }
